# Generated by Django 5.1.1 on 2024-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', 'uz'), ('en', 'en'), ('ru', 'ru')], default='uz', max_length=2),
        ),
    ]
